### ISSUE TITLE
Typo in branch name

### ISSUE THREAD

**Issue by a-l-e-c** [paslandau/paslandau.github.io#1]
https://github.com/paslandau/paslandau.github.io/blob/ad86d17c35af84e183eade7bdbd4ef19c2da4e9d/blog/docker-from-scratch-for-php-applications-in-2022/index.html#L319

Should be `part-4-1-docker-from-scratch-for-php-applications-in-2022`

**Comment by paslandau** [comment]
Thx, fixed
